#!bin/bash
# Downloads new file from specified location if the file
# does not exist or has not been modified within the last 
# 24 hours

function file_older_than_24hrs {
    
    # Checks if the files exists
    if [ ! -f "$1" ] ; then
        return 0
    fi 

    # Reads last time data file was modified in epoch
    old_time=`date -d "$(date -r $1 +"%Y-%m-%d %H:%M:%S")" +%s`

    # Reads current time in epoch
    now_time=`date +%s`

    # Checks if it has been more than 24 hours since data was last downloaded
    if [ `(echo "$now_time-$old_time") | bc` -gt 86400 ] ; then # 86400 seconds in 24 hours
        return 0
    else
        return 1
    fi

}