#!/bin/bash
#
# Author: Stephen Mitchell
# Date: 09/13/2020

function parse_nyt_data {
    ## Parses the New York Times's covid data us-counties.csv and creates a
    ## .json file for the specified county.
    ##
    ## USAGE:
    ##
    ##      csv_to_json (County,State) (Filename)
    ##

    # Greps for COUNTY,STATE 
    cat us-counties.csv | grep -i "$1" > smaller_csv.csv 

    # Replace DATE,COUNTY,STATE,NUMBER,CASES,DEATHS with ["DATE",CASES],
    regex="s/([[:digit:]]+-[[:digit:]]+-[[:digit:]]+),[$1]+,[[:digit:]]+,([[:digit:]]+),[[:digit:]]+/[\"\1\", \2],/ig"
    sed -r "$regex" smaller_csv.csv > "$2".json 

    # Replace first [ with [[ to make it valid json 
    # The -i.bak is for OSX compatability
    sed -i.bak "1 s/^\[/[[/" "$2".json && rm "$2".json.bak 

    # Replace last , with a ] to make it valid json
    sed -i.bak "$ s/,$/]/" "$2".json && rm "$2".json.bak

    # Removes temp files
    rm smaller_csv.csv 

    printf "New file created $2.json\n"
}